<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.26">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Report_Sensitivity</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="Report_Sensitivity_files/libs/clipboard/clipboard.min.js"></script>
<script src="Report_Sensitivity_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="Report_Sensitivity_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="Report_Sensitivity_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="Report_Sensitivity_files/libs/quarto-html/popper.min.js"></script>
<script src="Report_Sensitivity_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Report_Sensitivity_files/libs/quarto-html/anchor.min.js"></script>
<link href="Report_Sensitivity_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Report_Sensitivity_files/libs/quarto-html/quarto-syntax-highlighting-587c61ba64f3a5504c4d52d930310e48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Report_Sensitivity_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Report_Sensitivity_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Report_Sensitivity_files/libs/bootstrap/bootstrap-9e3ffae467580fdb927a41352e75a2e0.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Report_Sensitivity</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="discrepancies-between-the-reported-and-implemented-analysis" class="level4">
<h4 class="anchored" data-anchor-id="discrepancies-between-the-reported-and-implemented-analysis">1. Discrepancies between the reported and implemented analysis</h4>
<p>The paper states that the dependent variable is log-transformed after adding a small constant (0.05) to accommodate zero trauma shares. Our replication indicates this is not what was implemented. We confirmed that the authors’ Stata code does not include the “+ 0.05” transformation step; accordingly, reproducing the published results does not require (and is not consistent with) a specification.</p>
<p>Instead, the published estimates are exactly reproduced when the outcome is constructed as follows: the log is taken only for strictly positive trauma shares, and observations with a trauma share of zero are not transformed into a finite log value but are treated as left-censored at a fixed censoring point on the log scale (approximately −3). This is a substantively different procedure from adding a constant before logging. Under the implemented approach, zeros contribute to the likelihood through a censoring assumption (“latent below the threshold”) rather than through an observed transformed value. Because this censoring step is central to the model’s interpretation and to how zeros are handled, the mismatch between the paper’s description and the implemented code is consequential.</p>
</section>
<section id="why-the-censored-tobitintreg-approach-is-conceptually-misaligned-with-the-data" class="level4">
<h4 class="anchored" data-anchor-id="why-the-censored-tobitintreg-approach-is-conceptually-misaligned-with-the-data">2. Why the censored Tobit/intreg approach is conceptually misaligned with the data</h4>
<p>Even if the specification were fully documented, a censored Tobit (interval regression) is conceptually difficult to justify for this outcome. The trauma measure is a proportion derived from counts—trauma cases observed out of the number of examined skeletons in a site–period. In this setting, a zero share typically means “0 cases out of examined,” not that an underlying continuous latent variable has been censored by a detection limit. Tobit’s key assumption—that there exists an unbounded latent normal outcome that can fall below a threshold and then becomes censored—does not naturally correspond to a “count out of” data-generating process.</p>
<p>A related concern is that the information content of a zero depends heavily on the denominator. Observing 0 cases out of a large provides much stronger evidence that the underlying rate is near zero than observing 0 cases out of a small . In a Tobit-with-censoring setup, the way zeros enter the likelihood is driven by an arbitrary censor point on a transformed latent scale (roughly equivalent to a 5% violence rate), rather than by the exact sampling probability implied by . This can blur meaningful differences between site–periods with very different sample sizes.</p>
<p>Finally, proportional/count outcomes have a mean–variance relationship dictated by binomial sampling (and often additional overdispersion). The Tobit framework assumes (on the latent scale) a constant-variance normal disturbance; analytic weights can rescale contributions to the likelihood, but they do not make the Tobit likelihood equivalent to the count-based sampling process that generated the data, nor do they automatically recover the correct dependence of variance on both and the mean.</p>
</section>
<section id="why-a-beta-binomial-model-is-conceptually-better" class="level4">
<h4 class="anchored" data-anchor-id="why-a-beta-binomial-model-is-conceptually-better">3. Why a beta-binomial model is conceptually better</h4>
<p>A beta-binomial model matches the structure of the data directly. It models the observed number of trauma cases out of examined individuals, with the probability of trauma linked to covariates (e.g., via a logit link). The binomial component handles the fact that the data are discrete counts bounded by ; the beta component allows to vary across site–periods beyond what a strict binomial would permit, capturing overdispersion that is plausible in aggregated bioarchaeological data.</p>
<p>This approach resolves the key conceptual issues above:</p>
<ul>
<li>Zeros are treated as ordinary outcomes with an exact probability , rather than as censored latent values requiring an arbitrary censor threshold.</li>
<li>Differences in denominators are handled natively through the likelihood: 0/500 and 0/10 are not treated as equivalent signals.</li>
<li>Predicted means remain within [0, 1] by construction.</li>
<li>Overdispersion can be modeled explicitly, which generally yields more credible uncertainty estimates than relying on a homoskedastic latent-normal assumption.</li>
</ul>
</section>
<section id="empirical-comparison" class="level3">
<h3 class="anchored" data-anchor-id="empirical-comparison">4. Empirical Comparison</h3>
<section id="comparing-model-fit-and-predictive-accuracy" class="level4">
<h4 class="anchored" data-anchor-id="comparing-model-fit-and-predictive-accuracy">4.1 Comparing Model Fit and Predictive Accuracy</h4>
<p>[cite_start]The analysis sample consists of <span class="math inline">\(N=82\)</span> site-period observations (34 zero-trauma cases)[cite: 52, 239, 240]. [cite_start]To implement the Beta-binomial model, continuous proportions were reconstructed into integer counts; the mean absolute rounding discrepancy was negligible (0.021), ensuring the count-based model validly represents the data[cite: 336].</p>
<p>[cite_start]Although the Tobit model yielded a lower AIC/BIC, these metrics are <strong>not comparable</strong> here because the models operate on entirely different outcome scales (continuous log-density vs.&nbsp;discrete counts)[cite: 164, 359]. We instead rely on “common-scale” predictive checks, which reveal catastrophic failures in the Tobit specification:</p>
<ul>
<li><strong>Predictive Validity (The “Exploding Mean” Failure):</strong> The Tobit model generates theoretically impossible predictions when projected back to the original scale. [cite_start]The weighted predicted mean trauma share for the Tobit model was <strong>2,330.16</strong>, compared to an observed weighted mean of <strong>0.091</strong>[cite: 579]. This massive error occurs because the Tobit model applies analytic weights to the <em>log-scale</em> variance; when back-transformed to the natural scale, this inflated variance creates a heavy right tail that does not exist in the bounded <span class="math inline">\([0,1]\)</span> data. [cite_start]In contrast, the Beta-binomial model predicted a weighted mean of <strong>0.121</strong>, accurately tracking the observed data[cite: 579].</li>
<li><strong>Zero-Inflation/Censoring:</strong> The Tobit model fundamentally misidentifies the frequency of zeros. [cite_start]It predicts a weighted zero rate of <strong>59.9%</strong>, whereas the observed weighted zero rate is only <strong>12.6%</strong>[cite: 579]. [cite_start]The Beta-binomial model successfully recovers the data structure with a predicted zero rate of <strong>16.4%</strong>[cite: 579].</li>
<li><strong>Residual Diagnostics:</strong> The Beta-binomial model shows no evidence of misspecification. [cite_start]DHARMa simulation-based diagnostics confirm the residuals conform to expected distributions (KS test <span class="math inline">\(p=0.59\)</span>) and that dispersion is correctly modeled (<span class="math inline">\(p=0.36\)</span>), with no significant zero-inflation (<span class="math inline">\(p=0.58\)</span>)[cite: 419, 436, 479, 499].</li>
</ul>
</section>
<section id="re-evaluating-the-papers-conclusions" class="level4">
<h4 class="anchored" data-anchor-id="re-evaluating-the-papers-conclusions">4.2 Re-evaluating the Paper’s Conclusions</h4>
<p>[cite_start]The choice of model alters the statistical significance of the findings, though not the direction of the effects (coefficient signs agree across all variables)[cite: 755]. The Beta-binomial analysis suggests that the “fine-grained” temporal fluctuations reported in the paper are likely Type I errors (false positives) driven by the Tobit model’s inability to account for sample size (<span class="math inline">\(N\)</span>).</p>
<p><strong>Table 1: Comparison of Statistical Significance (<span class="math inline">\(p &lt; 0.05\)</span>)</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Variable</th>
<th style="text-align: left;">Context</th>
<th style="text-align: left;">Tobit (Original)</th>
<th style="text-align: left;">Beta-Binomial (Corrected)</th>
<th style="text-align: left;">Conclusion</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>Battle</strong></td>
<td style="text-align: left;">Violence</td>
<td style="text-align: left;"><strong>Sig</strong> (<span class="math inline">\(p=.009\)</span>)</td>
<td style="text-align: left;"><strong>Sig</strong> (<span class="math inline">\(p=.002\)</span>)</td>
<td style="text-align: left;"><strong>Robust</strong></td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Royal</strong></td>
<td style="text-align: left;">Status</td>
<td style="text-align: left;"><strong>Sig</strong> (<span class="math inline">\(p&lt;.001\)</span>)</td>
<td style="text-align: left;"><strong>Sig</strong> (<span class="math inline">\(p&lt;.001\)</span>)</td>
<td style="text-align: left;"><strong>Robust</strong></td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>T3bm</strong></td>
<td style="text-align: left;">Period 3</td>
<td style="text-align: left;"><strong>Sig</strong> (<span class="math inline">\(p=.011\)</span>)</td>
<td style="text-align: left;"><strong>Sig</strong> (<span class="math inline">\(p=.040\)</span>)</td>
<td style="text-align: left;"><strong>Robust</strong></td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Ton</strong></td>
<td style="text-align: left;">Period 1</td>
<td style="text-align: left;"><strong>Sig</strong> (<span class="math inline">\(p&lt;.001\)</span>)</td>
<td style="text-align: left;">NS (<span class="math inline">\(p=.521\)</span>)</td>
<td style="text-align: left;"><strong>Refuted</strong></td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>T2be</strong></td>
<td style="text-align: left;">Period 2</td>
<td style="text-align: left;"><strong>Sig</strong> (<span class="math inline">\(p=.001\)</span>)</td>
<td style="text-align: left;">NS (<span class="math inline">\(p=.854\)</span>)</td>
<td style="text-align: left;"><strong>Refuted</strong></td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>T5i</strong></td>
<td style="text-align: left;">Period 5</td>
<td style="text-align: left;"><strong>Sig</strong> (<span class="math inline">\(p&lt;.001\)</span>)</td>
<td style="text-align: left;">NS (<span class="math inline">\(p=.663\)</span>)</td>
<td style="text-align: left;"><strong>Refuted</strong></td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>co2ms</strong></td>
<td style="text-align: left;">Isotopes</td>
<td style="text-align: left;"><strong>Sig</strong> (<span class="math inline">\(p=.005\)</span>)</td>
<td style="text-align: left;">NS (<span class="math inline">\(p=.051\)</span>)</td>
<td style="text-align: left;"><strong>Refuted</strong></td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>co2l</strong></td>
<td style="text-align: left;">Isotopes</td>
<td style="text-align: left;">NS (<span class="math inline">\(p=.165\)</span>)</td>
<td style="text-align: left;"><strong>Sig</strong> (<span class="math inline">\(p=.030\)</span>)</td>
<td style="text-align: left;"><strong>New Finding</strong></td>
</tr>
</tbody>
</table>
<p><em>Note: P-values derived from cluster-robust errors. [cite_start]“Refuted” indicates that significance disappears or becomes borderline when using the appropriate count model.</em> [cite: 755]</p>
<p><strong>A. Conclusions Supported by Both Models (Robust):</strong> * [cite_start]<strong>Violence &amp; Status:</strong> Both models agree that <code>battle</code> and <code>royal</code> contexts are associated with significantly higher trauma prevalence[cite: 755]. * [cite_start]<strong>Period T3bm:</strong> Both models identify the <code>T3bm</code> period as having significantly lower trauma than the baseline[cite: 755].</p>
<p><strong>B. Conclusions Not Supported (Likely False Positives):</strong> The Tobit model identified three other periods (<code>Ton_</code>, <code>T2be</code>, <code>T5i_</code>) as having significantly lower trauma rates. <strong>The Beta-binomial model finds no evidence for this</strong>, suggesting these effects were artifacts of treating small-sample zeros as high-certainty data points. * [cite_start]<code>Ton_</code>: <span class="math inline">\(p\)</span> increases from <span class="math inline">\(&lt;0.001\)</span> (Tobit) to <strong>0.521</strong> (Beta-binomial/NS)[cite: 755]. * [cite_start]<code>T2be</code>: <span class="math inline">\(p\)</span> increases from <span class="math inline">\(0.001\)</span> (Tobit) to <strong>0.854</strong> (Beta-binomial/NS)[cite: 755]. * [cite_start]<code>T5i_</code>: <span class="math inline">\(p\)</span> increases from <span class="math inline">\(&lt;0.001\)</span> (Tobit) to <strong>0.663</strong> (Beta-binomial/NS)[cite: 755].</p>
<p><strong>C. New Insights:</strong> * <strong>Carbon Isotopes:</strong> The model choice flips the significance of isotope proxies. [cite_start]In the Beta-binomial model, <code>co2l</code> (low Carbon) becomes a significant negative predictor (<span class="math inline">\(p=0.030\)</span>), while the <code>co2ms</code> effect found in the Tobit model fades to non-significance (<span class="math inline">\(p=0.051\)</span>)[cite: 755].</p>
<p><strong>Summary:</strong> The robust evidence indicates a simpler story than originally claimed: violence spikes in specific contexts (Battles, Royal) and dips in <code>T3bm</code>, but other periods are statistically indistinguishable from the baseline once sample size is properly modeled.</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>